"""empty message

Revision ID: d33281a42967
Revises: 
Create Date: 2017-11-19 21:32:13.192811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33281a42967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KeyWord',
    sa.Column('pk_KeyWord', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('modificationDate', sa.DateTime(), nullable=True),
    sa.Column('curStatus', sa.Integer(), nullable=False),
    sa.Column('lng', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('pk_KeyWord')
    )
    op.create_table('ConfiguratedInput',
    sa.Column('pk_ConfiguratedInput', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('labelFr', sa.String(length=300, collation='BINARY'), nullable=False),
    sa.Column('labelEn', sa.String(length=300, collation='BINARY'), nullable=False),
    sa.Column('editMode', sa.Integer(), nullable=False),
    sa.Column('fieldSize', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('atBeginingOfLine', sa.Boolean(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('curStatus', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('editorClass', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('fieldClassEdit', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('fieldClassDisplay', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('originalID', sa.BigInteger(), nullable=True),
    sa.Column('linkedFieldTable', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('linkedField', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('linkedFieldset', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.PrimaryKeyConstraint('pk_ConfiguratedInput')
    )
    op.create_table('Form',
    sa.Column('pk_Form', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('tag', sa.String(length=300, collation='BINARY'), nullable=True),
    sa.Column('labelFr', sa.String(length=300, collation='BINARY'), nullable=False),
    sa.Column('labelEn', sa.String(length=300, collation='BINARY'), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('modificationDate', sa.DateTime(), nullable=True),
    sa.Column('curStatus', sa.Integer(), nullable=False),
    sa.Column('descriptionFr', sa.String(length=300, collation='BINARY'), nullable=False),
    sa.Column('descriptionEn', sa.String(length=300, collation='BINARY'), nullable=False),
    sa.Column('obsolete', sa.Boolean(), nullable=False),
    sa.Column('isTemplate', sa.Boolean(), nullable=False),
    sa.Column('context', sa.String(length=50, collation='BINARY'), nullable=False),
    sa.Column('originalID', sa.Integer(), nullable=True),
    sa.Column('propagate', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk_Form'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Unity',
    sa.Column('pk_Unity', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('labelFr', sa.String(length=300, collation='BINARY'), nullable=True),
    sa.Column('labelEn', sa.String(length=300, collation='BINARY'), nullable=True),
    sa.Column('context', sa.String(length=50, collation='BINARY'), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk_Unity')
    )
    op.create_table('ConfiguratedInputProperty',
    sa.Column('pk_ConfiguratedInputProperty', sa.BigInteger(), nullable=False),
    sa.Column('fk_ConfiguratedInput', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255, collation=''), nullable=False),
    sa.Column('value', sa.String(length=5000, collation='BINARY'), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('valueType', sa.String(length=10, collation='BINARY'), nullable=False),
    sa.ForeignKeyConstraint(['fk_ConfiguratedInput'], ['ConfiguratedInput.pk_ConfiguratedInput'], ),
    sa.PrimaryKeyConstraint('pk_ConfiguratedInputProperty')
    )
    op.create_table('Fieldset',
    sa.Column('pk_Fieldset', sa.BigInteger(), nullable=False),
    sa.Column('fk_form', sa.BigInteger(), nullable=False),
    sa.Column('legend', sa.String(length=255, collation='BINARY'), nullable=False),
    sa.Column('fields', sa.String(length=255, collation='BINARY'), nullable=False),
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('curStatus', sa.Integer(), nullable=False),
    sa.Column('refid', sa.String(length=255, collation='BINARY'), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fk_form'], ['Form.pk_Form'], ),
    sa.PrimaryKeyConstraint('pk_Fieldset')
    )
    op.create_table('FormFile',
    sa.Column('Pk_ID', sa.BigInteger(), nullable=False),
    sa.Column('fk_form', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=300, collation='BINARY'), nullable=True),
    sa.Column('filedata', sa.VARBINARY(length=255), nullable=False),
    sa.ForeignKeyConstraint(['fk_form'], ['Form.pk_Form'], ),
    sa.PrimaryKeyConstraint('Pk_ID')
    )
    op.create_table('KeyWord_Form',
    sa.Column('pk_KeyWord_Form', sa.BigInteger(), nullable=False),
    sa.Column('fk_KeyWord', sa.BigInteger(), nullable=False),
    sa.Column('fk_Form', sa.BigInteger(), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('curStatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_Form'], ['Form.pk_Form'], ),
    sa.ForeignKeyConstraint(['fk_KeyWord'], ['KeyWord.pk_KeyWord'], ),
    sa.PrimaryKeyConstraint('pk_KeyWord_Form')
    )
    op.create_table('Input',
    sa.Column('pk_Input', sa.BigInteger(), nullable=False),
    sa.Column('fk_form', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('labelFr', sa.String(length=300, collation='BINARY'), nullable=False),
    sa.Column('labelEn', sa.String(length=300, collation='BINARY'), nullable=False),
    sa.Column('editMode', sa.Integer(), nullable=False),
    sa.Column('fieldSize', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('atBeginingOfLine', sa.Boolean(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('curStatus', sa.Integer(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.Column('type', sa.String(length=100, collation='BINARY'), nullable=False),
    sa.Column('editorClass', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('fieldClassEdit', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('fieldClassDisplay', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('originalID', sa.BigInteger(), nullable=True),
    sa.Column('linkedFieldTable', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('linkedField', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.Column('linkedFieldset', sa.String(length=100, collation='BINARY'), nullable=True),
    sa.ForeignKeyConstraint(['fk_form'], ['Form.pk_Form'], ),
    sa.PrimaryKeyConstraint('pk_Input')
    )
    op.create_table('FormProperty',
    sa.Column('pk_FormProperty', sa.BigInteger(), nullable=False),
    sa.Column('fk_Form', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255, collation='BINARY'), nullable=False),
    sa.Column('value', sa.String(length=255, collation='BINARY'), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('valueType', sa.String(length=10, collation='BINARY'), nullable=False),
    sa.ForeignKeyConstraint(['fk_Form'], ['Form.pk_Form'], ),
    sa.PrimaryKeyConstraint('pk_FormProperty')
    )
    op.create_table('InputProperty',
    sa.Column('pk_InputProperty', sa.BigInteger(), nullable=False),
    sa.Column('fk_Input', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255, collation='BINARY'), nullable=False),
    sa.Column('value', sa.String(length=5000, collation='BINARY'), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('valueType', sa.String(length=10, collation='BINARY'), nullable=False),
    sa.ForeignKeyConstraint(['fk_Input'], ['Input.pk_Input'], ),
    sa.PrimaryKeyConstraint('pk_InputProperty')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('InputProperty')
    op.drop_table('FormProperty')
    op.drop_table('Input')
    op.drop_table('KeyWord_Form')
    op.drop_table('FormFile')
    op.drop_table('Fieldset')
    op.drop_table('ConfiguratedInputProperty')
    op.drop_table('Unity')
    op.drop_table('Form')
    op.drop_table('ConfiguratedInput')
    op.drop_table('KeyWord')
    # ### end Alembic commands ###
